layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    - Py-Template
    - osandadeemantha
    - mvn-artifacts

social_media:
  # behance: your_username
  # dribbble: your_username
  linkedin: osanda-d
  medium: osa_
  facebook: osandadh
  # hackerrank: your_username
  instagram: osanda_dee
  # keybase: your_username
  # mastodon: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: OsandaDeemantha
  # unsplash: your_username
  # vk: your_username
  # website: https://osandadeemantha.github.io
  # youtube: your_username

topics:
  - name: AWS
    web_url: https://aws.amazon.com/
    image_url: https://raw.githubusercontent.com/github/explore/fbceb94436312b6dacde68d122a5b9c7d11f9524/topics/aws/aws.png

  - name: Docker
    web_url: https://www.docker.com/
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/docker/docker.png

  - name: Kubernetes
    web_url: https://kubernetes.io/
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/kubernetes/kubernetes.png

  - name: Spring Boot
    web_url: https://spring.io/projects/spring-boot
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/spring-boot/spring-boot.png

  - name: Angular
    web_url: https://angular.io/
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/angular/angular.png

  - name: Express
    web_url: https://expressjs.com/
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/express/express.png
